### PR TITLE
Preliminaries page

### PR DESCRIPTION
**Pull request by JobDoesburg**

### CODE REVIEW

**Comment by JobDoesburg** [comment]
Did it wrong again...

**Comment by RagnarGrootKoerkamp** [comment]
I don't think we should modify the 2018 BAPC page anymore. Any changes to the master branch here are automatically pushed to 2018.bapc.eu, which should remain as it is IMO.

It's probably best if you/Thalia just create a new repository. (Or we could create a new 2019 branch here, but I don't see that much point in that.)

**Comment by RagnarGrootKoerkamp** [comment]
> Did it wrong again

Oh, nvm then. What was your intent?

**Comment by JobDoesburg** [comment]
I accidentally made a PR to the 2018 website, should have been to the 2019 website.

**Comment by JobDoesburg** [comment]
> I don't think we should modify the 2018 BAPC page anymore. Any changes to the master branch here are automatically pushed to 2018.bapc.eu, which should remain as it is IMO.
> 
> It's probably best if you/Thalia just create a new repository. (Or we could create a new 2019 branch here, but I don't see that much point in that.)

@pingiun can you consider this

**Comment by pingiun** [comment]
There was just a problem with github, which automatically chooses the base of a fork for a PR, while our [own repository](https://github.com/pingiun/BAPC2019-website) should have been used.

**Pull request closed without merging**
